### ISSUE TITLE
Event is not triggered when entering element

### ISSUE THREAD

**Issue by peterclio** [lolmaus/jquery.dragbetter#5]
I just tried a simple setup, similar to the one described here.
And it doesn't always trigger the even when I start dragging over the BODY tag.

Tested in Firefox 3.1, IE 11.0.12 & Chrome 37.0.2062.103

If I inspect the test setup using Firebug, I can see that the BODY tag doesn't cover the entire page. (Even if background color does.), so this might be why it doesn't trigger when I drag something frm the below the browser.

**Comment by lolmaus** [comment]
Probably, you're doing something wrong.

It's hard to say what specifically until i have a look at your code. Please share a minimal demonstration of the problem via http://jsbin.com/ .

Here's mine and it's working fine: http://jsbin.com/xexub/1/edit?html,css,js,output

**Comment by peterclio** [comment]
Using the HTML tag instad of BODY tag solves the problem..

**Comment by lolmaus** [comment]
You probably didn't have `<body>` stretched to window size, it was as small as the content.

HTML has special treatment for the `<html>` and `<body>` elements. The `background` CSS property applied to those elements is actually applied on the window instead.

Have a look at this to get the idea of what's going on: http://jsbin.com/yoran/1/edit?html,css,output

Do this to resolve the problem:

``` css
html, body {
  width: 100%;
  height: 100%;
}
```

**Comment by peterclio** [comment]
Here's my testsetup:
http://jsbin.com/rurosabicupu/1/edit

I also included a screenshot, so you can see what I mean by the body tag not covering the entire page..
https://imgur.com/AAHQJpz

**Comment by lolmaus** [comment]
I've already explained the reason behind that behavior and a way to resolve it.
